### ISSUE TITLE
Stop at beginning 

### ISSUE THREAD

**Issue by rainfalj** [Hwang64/MLKP#2]
Loading pretrained model weights from data/ImageNet_models/VGG16.v2.caffemodel
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553432430
I0411 11:19:13.488446 29051 net.cpp:816] Ignoring source layer pool5
I0411 11:19:13.604282 29051 net.cpp:816] Ignoring source layer fc8
I0411 11:19:13.604317 29051 net.cpp:816] Ignoring source layer prob
Solving...
Wrote snapshot to: MLKP/output/faster_rcnn_end2end/voc_2007_trainval+voc_2012_trainval/vgg16_mlkp_iter_0.caffemodel
done solving

**Comment by foralliance** [comment]
@rainfalj  HI
when u build the cython modules，whether the following situation occurs.
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
rm -rf build

This leads to test, prompting:
Traceback (most recent call last):
File "./tools/test_net.py", line 13, in
from fast_rcnn.test import test_net
File "/home/jmx/MLKP/tools/../lib/fast_rcnn/test.py", line 17, in
from fast_rcnn.nms_wrapper import nms, soft_nms
File "/home/jmx/MLKP/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in
from nms.gpu_nms import gpu_nms
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

**Comment by rainfalj** [comment]
I use cuda8.0 and it's ok when building the cython modules

**Comment by Hwang64** [comment]
@rainfalj I think you should type in the iteration parameter when training the network, I have refreshed the readme.txt and maybe you can try it.

**Comment by Hwang64** [comment]
@foralliance I think you should remove the files cpu_nms.so and gpu_num.so in path:/lib/nms/ firstly, and rebuilt it, you can try it and if there are still some problems, please contact me.

**Comment by rainfalj** [comment]
@Hwang64 I type the iteration parameter:python ./tools/train_net.py --gpu 0 --solver models/VGG16/solver.prototxt --weights data/ImageNet_models/VGG16.v2.caffemodel --imdb voc_2007_trainval+voc_2012_trainval --cfg experiments/cfgs/faster_rcnn_end2end.yml --iters 150000 and it still stopped at beginning.  It seems like the caffe of this version problem

**Comment by foralliance** [comment]
@Hwang64 
According to your method, after deleting two files, my problem was solved.

@rainfalj @Hwang64 
For the training problem you pointed out. The problem can be solved after reducing the learning rate from 1e-3 to 1e-7.

when the learning rate is 1e-3. my problem is:
I0416 14:38:01.644944 22611 net.cpp:283] Network initialization done.
I0416 14:38:01.645406 22611 solver.cpp:60] Solver scaffolding done.
Loading pretrained model weights from data/ImageNet_models/VGG16.v2.caffemodel
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553432430
I0416 14:38:01.909946 22611 net.cpp:816] Ignoring source layer pool5
I0416 14:38:02.027390 22611 net.cpp:816] Ignoring source layer fc8
I0416 14:38:02.027410 22611 net.cpp:816] Ignoring source layer prob
Solving...
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in exp
  pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in multiply
  pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in exp
  pred_h = np.exp(dh) * heights[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in multiply
  pred_h = np.exp(dh) * heights[:, np.newaxis]
I0416 14:38:03.034277 22611 solver.cpp:229] Iteration 0, loss = 14094.8
I0416 14:38:03.034312 22611 solver.cpp:245]     Train net output #0: accuarcy = 0.5
I0416 14:38:03.034320 22611 solver.cpp:245]     Train net output #1: loss_bbox = 1932.72 (* 1 = 1932.72 loss)
I0416 14:38:03.034325 22611 solver.cpp:245]     Train net output #2: loss_cls = 43.6683 (* 1 = 43.6683 loss)
I0416 14:38:03.034330 22611 solver.cpp:245]     Train net output #3: rpn_cls_loss = 40.2567 (* 1 = 40.2567 loss)
I0416 14:38:03.034334 22611 solver.cpp:245]     Train net output #4: rpn_loss_bbox = 3507.18 (* 1 = 3507.18 loss)
I0416 14:38:03.034340 22611 sgd_solver.cpp:106] Iteration 0, lr = 0.001
/home/jmx/MLKP/tools/../lib/rpn/proposal_layer.py:179: RuntimeWarning: invalid value encountered in greater_equal
  keep = np.where((ws >= min_size_fx) & (hs >= min_size_fy))[0]
./train.sh: 行 6: 22611 浮点数例外         (核心已转储) python tools/train_net.py --gpu 0 --solver models/VGG16/solver.prototxt --weights data/ImageNet_models/VGG16.v2.caffemodel --imdb voc_2007_trainval+voc_2012_trainval --cfg experiments/cfgs/faster_rcnn_end2end.yml


when the learning rate is 1e-7,
I0416 14:41:32.035742 22738 net.cpp:283] Network initialization done.
I0416 14:41:32.035881 22738 solver.cpp:60] Solver scaffolding done.
Loading pretrained model weights from data/ImageNet_models/VGG16.v2.caffemodel
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553432430
I0416 14:41:32.288107 22738 net.cpp:816] Ignoring source layer pool5
I0416 14:41:32.384312 22738 net.cpp:816] Ignoring source layer fc8
I0416 14:41:32.384328 22738 net.cpp:816] Ignoring source layer prob
Solving...
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in exp
  pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in multiply
  pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in exp
  pred_h = np.exp(dh) * heights[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in multiply
  pred_h = np.exp(dh) * heights[:, np.newaxis]
I0416 14:41:33.417304 22738 solver.cpp:229] Iteration 0, loss = 14094.8
I0416 14:41:33.417335 22738 solver.cpp:245]     Train net output #0: accuarcy = 0.5
I0416 14:41:33.417345 22738 solver.cpp:245]     Train net output #1: loss_bbox = 1932.72 (* 1 = 1932.72 loss)
I0416 14:41:33.417349 22738 solver.cpp:245]     Train net output #2: loss_cls = 43.6683 (* 1 = 43.6683 loss)
I0416 14:41:33.417354 22738 solver.cpp:245]     Train net output #3: rpn_cls_loss = 40.2567 (* 1 = 40.2567 loss)
I0416 14:41:33.417361 22738 solver.cpp:245]     Train net output #4: rpn_loss_bbox = 3507.18 (* 1 = 3507.18 loss)
I0416 14:41:33.417364 22738 sgd_solver.cpp:106] Iteration 0, lr = 1e-07
I0416 14:41:46.487526 22738 solver.cpp:229] Iteration 20, loss = 188.21
I0416 14:41:46.487560 22738 solver.cpp:245]     Train net output #0: accuarcy = 0.5
I0416 14:41:46.487568 22738 solver.cpp:245]     Train net output #1: loss_bbox = 2.87174 (* 1 = 2.87174 loss)
I0416 14:41:46.487573 22738 solver.cpp:245]     Train net output #2: loss_cls = 8.51138 (* 1 = 8.51138 loss)
I0416 14:41:46.487578 22738 solver.cpp:245]     Train net output #3: rpn_cls_loss = 1.3526 (* 1 = 1.3526 loss)
I0416 14:41:46.487583 22738 solver.cpp:245]     Train net output #4: rpn_loss_bbox = 0.206488 (* 1 = 0.206488 loss)
I0416 14:41:46.487588 22738 sgd_solver.cpp:106] Iteration 20, lr = 1e-07
I0416 14:41:59.602818 22738 solver.cpp:229] Iteration 40, loss = 14.8165
I0416 14:41:59.602844 22738 solver.cpp:245]     Train net output #0: accuarcy = 0.273438
I0416 14:41:59.602852 22738 solver.cpp:245]     Train net output #1: loss_bbox = 8.75156 (* 1 = 8.75156 loss)
I0416 14:41:59.602856 22738 solver.cpp:245]     Train net output #2: loss_cls = 6.32691 (* 1 = 6.32691 loss)
I0416 14:41:59.602860 22738 solver.cpp:245]     Train net output #3: rpn_cls_loss = 0.456521 (* 1 = 0.456521 loss)
I0416 14:41:59.602864 22738 solver.cpp:245]     Train net output #4: rpn_loss_bbox = 0.0281576 (* 1 = 0.0281576 loss)
I0416 14:41:59.602867 22738 sgd_solver.cpp:106] Iteration 40, lr = 1e-07
I0416 14:42:12.923100 22738 solver.cpp:229] Iteration 60, loss = 8.62598
I0416 14:42:12.923126 22738 solver.cpp:245]     Train net output #0: accuarcy = 0.351562
I0416 14:42:12.923133 22738 solver.cpp:245]     Train net output #1: loss_bbox = 0.627917 (* 1 = 0.627917 loss)
I0416 14:42:12.923136 22738 solver.cpp:245]     Train net output #2: loss_cls = 3.58328 (* 1 = 3.58328 loss)
I0416 14:42:12.923141 22738 solver.cpp:245]     Train net output #3: rpn_cls_loss = 0.525151 (* 1 = 0.525151 loss)
I0416 14:42:12.923144 22738 solver.cpp:245]     Train net output #4: rpn_loss_bbox = 0.0781858 (* 1 = 0.0781858 loss)
I0416 14:42:12.923147 22738 sgd_solver.cpp:106] Iteration 60, lr = 1e-07
I0416 14:42:26.255865 22738 solver.cpp:229] Iteration 80, loss = 3.78171
I0416 14:42:26.255892 22738 solver.cpp:245]     Train net output #0: accuarcy = 0.390625
I0416 14:42:26.255899 22738 solver.cpp:245]     Train net output #1: loss_bbox = 0.220015 (* 1 = 0.220015 loss)
I0416 14:42:26.255903 22738 solver.cpp:245]     Train net output #2: loss_cls = 2.28895 (* 1 = 2.28895 loss)
I0416 14:42:26.255908 22738 solver.cpp:245]     Train net output #3: rpn_cls_loss = 0.507528 (* 1 = 0.507528 loss)
I0416 14:42:26.255911 22738 solver.cpp:245]     Train net output #4: rpn_loss_bbox = 0.00543731 (* 1 = 0.00543731 loss)
I0416 14:42:26.255914 22738 sgd_solver.cpp:106] Iteration 80, lr = 1e-07

Now, you can train successfully.

Another question, what does the following information represent?
```

/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in exp
  pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in multiply
  pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in exp
  pred_h = np.exp(dh) * heights[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in multiply
  pred_h = np.exp(dh) * heights[:, np.newaxis]
```

**Comment by foralliance** [comment]
@Hwang64
According to your method, after deleting two files, my problem was solved.

@rainfalj @Hwang64
For the training problem you pointed out. The problem can be solved after reducing the learning rate from 1e-3 to 1e-7.

when the learning rate is 1e-3. my problem is:
```
I0416 14:38:01.644944 22611 net.cpp:283] Network initialization done.
I0416 14:38:01.645406 22611 solver.cpp:60] Solver scaffolding done.
Loading pretrained model weights from data/ImageNet_models/VGG16.v2.caffemodel
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message. If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons. To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553432430
I0416 14:38:01.909946 22611 net.cpp:816] Ignoring source layer pool5
I0416 14:38:02.027390 22611 net.cpp:816] Ignoring source layer fc8
I0416 14:38:02.027410 22611 net.cpp:816] Ignoring source layer prob
Solving...
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in exp
pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in multiply
pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in exp
pred_h = np.exp(dh) * heights[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in multiply
pred_h = np.exp(dh) * heights[:, np.newaxis]
I0416 14:38:03.034277 22611 solver.cpp:229] Iteration 0, loss = 14094.8
I0416 14:38:03.034312 22611 solver.cpp:245] Train net output #0: accuarcy = 0.5
I0416 14:38:03.034320 22611 solver.cpp:245] Train net output #1: loss_bbox = 1932.72 (* 1 = 1932.72 loss)
I0416 14:38:03.034325 22611 solver.cpp:245] Train net output #2: loss_cls = 43.6683 (* 1 = 43.6683 loss)
I0416 14:38:03.034330 22611 solver.cpp:245] Train net output #3: rpn_cls_loss = 40.2567 (* 1 = 40.2567 loss)
I0416 14:38:03.034334 22611 solver.cpp:245] Train net output #4: rpn_loss_bbox = 3507.18 (* 1 = 3507.18 loss)
I0416 14:38:03.034340 22611 sgd_solver.cpp:106] Iteration 0, lr = 0.001
/home/jmx/MLKP/tools/../lib/rpn/proposal_layer.py:179: RuntimeWarning: invalid value encountered in greater_equal
keep = np.where((ws >= min_size_fx) & (hs >= min_size_fy))[0]
./train.sh: 行 6: 22611 浮点数例外 (核心已转储) python tools/train_net.py --gpu 0 --solver models/VGG16/solver.prototxt --weights data/ImageNet_models/VGG16.v2.caffemodel --imdb voc_2007_trainval+voc_2012_trainval --cfg experiments/cfgs/faster_rcnn_end2end.yml
```

when the learning rate is 1e-7,
```
I0416 14:41:32.035742 22738 net.cpp:283] Network initialization done.
I0416 14:41:32.035881 22738 solver.cpp:60] Solver scaffolding done.
Loading pretrained model weights from data/ImageNet_models/VGG16.v2.caffemodel
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message. If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons. To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553432430
I0416 14:41:32.288107 22738 net.cpp:816] Ignoring source layer pool5
I0416 14:41:32.384312 22738 net.cpp:816] Ignoring source layer fc8
I0416 14:41:32.384328 22738 net.cpp:816] Ignoring source layer prob
Solving...
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in exp
pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in multiply
pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in exp
pred_h = np.exp(dh) * heights[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in multiply
pred_h = np.exp(dh) * heights[:, np.newaxis]
I0416 14:41:33.417304 22738 solver.cpp:229] Iteration 0, loss = 14094.8
I0416 14:41:33.417335 22738 solver.cpp:245] Train net output #0: accuarcy = 0.5
I0416 14:41:33.417345 22738 solver.cpp:245] Train net output #1: loss_bbox = 1932.72 (* 1 = 1932.72 loss)
I0416 14:41:33.417349 22738 solver.cpp:245] Train net output #2: loss_cls = 43.6683 (* 1 = 43.6683 loss)
I0416 14:41:33.417354 22738 solver.cpp:245] Train net output #3: rpn_cls_loss = 40.2567 (* 1 = 40.2567 loss)
I0416 14:41:33.417361 22738 solver.cpp:245] Train net output #4: rpn_loss_bbox = 3507.18 (* 1 = 3507.18 loss)
I0416 14:41:33.417364 22738 sgd_solver.cpp:106] Iteration 0, lr = 1e-07
I0416 14:41:46.487526 22738 solver.cpp:229] Iteration 20, loss = 188.21
I0416 14:41:46.487560 22738 solver.cpp:245] Train net output #0: accuarcy = 0.5
I0416 14:41:46.487568 22738 solver.cpp:245] Train net output #1: loss_bbox = 2.87174 (* 1 = 2.87174 loss)
I0416 14:41:46.487573 22738 solver.cpp:245] Train net output #2: loss_cls = 8.51138 (* 1 = 8.51138 loss)
I0416 14:41:46.487578 22738 solver.cpp:245] Train net output #3: rpn_cls_loss = 1.3526 (* 1 = 1.3526 loss)
I0416 14:41:46.487583 22738 solver.cpp:245] Train net output #4: rpn_loss_bbox = 0.206488 (* 1 = 0.206488 loss)
I0416 14:41:46.487588 22738 sgd_solver.cpp:106] Iteration 20, lr = 1e-07
I0416 14:41:59.602818 22738 solver.cpp:229] Iteration 40, loss = 14.8165
I0416 14:41:59.602844 22738 solver.cpp:245] Train net output #0: accuarcy = 0.273438
I0416 14:41:59.602852 22738 solver.cpp:245] Train net output #1: loss_bbox = 8.75156 (* 1 = 8.75156 loss)
I0416 14:41:59.602856 22738 solver.cpp:245] Train net output #2: loss_cls = 6.32691 (* 1 = 6.32691 loss)
I0416 14:41:59.602860 22738 solver.cpp:245] Train net output #3: rpn_cls_loss = 0.456521 (* 1 = 0.456521 loss)
I0416 14:41:59.602864 22738 solver.cpp:245] Train net output #4: rpn_loss_bbox = 0.0281576 (* 1 = 0.0281576 loss)
I0416 14:41:59.602867 22738 sgd_solver.cpp:106] Iteration 40, lr = 1e-07
I0416 14:42:12.923100 22738 solver.cpp:229] Iteration 60, loss = 8.62598
I0416 14:42:12.923126 22738 solver.cpp:245] Train net output #0: accuarcy = 0.351562
I0416 14:42:12.923133 22738 solver.cpp:245] Train net output #1: loss_bbox = 0.627917 (* 1 = 0.627917 loss)
I0416 14:42:12.923136 22738 solver.cpp:245] Train net output #2: loss_cls = 3.58328 (* 1 = 3.58328 loss)
I0416 14:42:12.923141 22738 solver.cpp:245] Train net output #3: rpn_cls_loss = 0.525151 (* 1 = 0.525151 loss)
I0416 14:42:12.923144 22738 solver.cpp:245] Train net output #4: rpn_loss_bbox = 0.0781858 (* 1 = 0.0781858 loss)
I0416 14:42:12.923147 22738 sgd_solver.cpp:106] Iteration 60, lr = 1e-07
I0416 14:42:26.255865 22738 solver.cpp:229] Iteration 80, loss = 3.78171
I0416 14:42:26.255892 22738 solver.cpp:245] Train net output #0: accuarcy = 0.390625
I0416 14:42:26.255899 22738 solver.cpp:245] Train net output #1: loss_bbox = 0.220015 (* 1 = 0.220015 loss)
I0416 14:42:26.255903 22738 solver.cpp:245] Train net output #2: loss_cls = 2.28895 (* 1 = 2.28895 loss)
I0416 14:42:26.255908 22738 solver.cpp:245] Train net output #3: rpn_cls_loss = 0.507528 (* 1 = 0.507528 loss)
I0416 14:42:26.255911 22738 solver.cpp:245] Train net output #4: rpn_loss_bbox = 0.00543731 (* 1 = 0.00543731 loss)
I0416 14:42:26.255914 22738 sgd_solver.cpp:106] Iteration 80, lr = 1e-07
```
Now, you can train successfully.

Another question, what does the following information represent?
```
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in exp
  pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:47: RuntimeWarning: overflow encountered in multiply
  pred_w = np.exp(dw) * widths[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in exp
  pred_h = np.exp(dh) * heights[:, np.newaxis]
/home/jmx/MLKP/tools/../lib/fast_rcnn/bbox_transform.py:48: RuntimeWarning: overflow encountered in multiply
  pred_h = np.exp(dh) * heights[:, np.newaxis]
```

**Comment by Hwang64** [comment]
@rainfalj 
@foralliance , Sorry for replying late, I have updated the model in /lib/model, the learning rate should be 1e-3, the same as the paper illustrate, you can update the model file and re-train your network, don't hesitate to contact me for any questions!

**Comment by foralliance** [comment]
@Hwang64 
According to your method, the problem was solved.

Compared to the two models, the change is  "train.prototxt". For example, for the VGG16 model, the difference between the two is that the initialization method of conv_T4 has changed.
Can you explain the reason for the error and why this method can avoid mistakes?

**Comment by foralliance** [comment]
@Hwang64 ,
According to your method, the problem was solved.

Compared to the two models, the change is "train.prototxt". 
Where did you change it?Can you explain the reason for the error and why this method can avoid mistakes?

**Comment by rainfalj** [comment]
@Hwang64 I think you should solve the "plt"  problem when the code is run without desktop. I  change the code and solve it now. closed

**Comment by Fckcoding** [comment]
@rainfalj Can you share your solution,please? I met the same question when run the code without desktop

**Comment by moyans** [comment]
The error ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory
maybe you cuda is 8.0 version，you can use this lines solve it.
`sudo ln -sf /usr/local/cuda/lib64/libcudart.so.8.0 /usr/local/cuda/lib64/libcudart.so.7.5`
